//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoCalc.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErgoCalc.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Accept.
        /// </summary>
        internal static string strBtnAccept {
            get {
                return ResourceManager.GetString("strBtnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string strBtnCancel {
            get {
                return ResourceManager.GetString("strBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string strBtnDlgFont {
            get {
                return ResourceManager.GetString("strBtnDlgFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string strBtnExample {
            get {
                return ResourceManager.GetString("strBtnExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset.
        /// </summary>
        internal static string strBtnReset {
            get {
                return ResourceManager.GetString("strBtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember open/save dialog previous path.
        /// </summary>
        internal static string strChkDlgPath {
            get {
                return ResourceManager.GetString("strChkDlgPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word wrap.
        /// </summary>
        internal static string strChkWordWrap {
            get {
                return ResourceManager.GetString("strChkWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset all fields
        ///to their default values?.
        /// </summary>
        internal static string strDlgReset {
            get {
                return ResourceManager.GetString("strDlgReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings?.
        /// </summary>
        internal static string strDlgResetTitle {
            get {
                return ResourceManager.GetString("strDlgResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select culture.
        /// </summary>
        internal static string strFormLanguageTitle {
            get {
                return ResourceManager.GetString("strFormLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErgoCalc.
        /// </summary>
        internal static string strFormMainTitle {
            get {
                return ResourceManager.GetString("strFormMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New model.
        /// </summary>
        internal static string strFormNewTitle {
            get {
                return ResourceManager.GetString("strFormNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLM model results.
        /// </summary>
        internal static string strFormResultsCLM {
            get {
                return ResourceManager.GetString("strFormResultsCLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LM-MMH model results.
        /// </summary>
        internal static string strFormResultsLiberty {
            get {
                return ResourceManager.GetString("strFormResultsLiberty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metabolic rate results.
        /// </summary>
        internal static string strFormResultsMetabolic {
            get {
                return ResourceManager.GetString("strFormResultsMetabolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIOSH model results.
        /// </summary>
        internal static string strFormResultsNIOSH {
            get {
                return ResourceManager.GetString("strFormResultsNIOSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCRA checklist model results.
        /// </summary>
        internal static string strFormResultsOCRAcheck {
            get {
                return ResourceManager.GetString("strFormResultsOCRAcheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strain Index model results.
        /// </summary>
        internal static string strFormResultsStrainIndex {
            get {
                return ResourceManager.GetString("strFormResultsStrainIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal comfort results.
        /// </summary>
        internal static string strFormResultsTC {
            get {
                return ResourceManager.GetString("strFormResultsTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WR model results.
        /// </summary>
        internal static string strFormResultsWR {
            get {
                return ResourceManager.GetString("strFormResultsWR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string strFormTitleUnion {
            get {
                return ResourceManager.GetString("strFormTitleUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom level.
        /// </summary>
        internal static string strFormZoom {
            get {
                return ResourceManager.GetString("strFormZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string strFrmSettings {
            get {
                return ResourceManager.GetString("strFrmSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language and culture options.
        /// </summary>
        internal static string strGrpCulture {
            get {
                return ResourceManager.GetString("strGrpCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current font.
        /// </summary>
        internal static string strGrpFont {
            get {
                return ResourceManager.GetString("strGrpFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back color: {0}.
        /// </summary>
        internal static string strLblBackColor {
            get {
                return ResourceManager.GetString("strLblBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric data-formatting string.
        /// </summary>
        internal static string strLblDataFormat {
            get {
                return ResourceManager.GetString("strLblDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change current font.
        /// </summary>
        internal static string strLblDlgFont {
            get {
                return ResourceManager.GetString("strLblDlgFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font color: {0}.
        /// </summary>
        internal static string strLblFontColor {
            get {
                return ResourceManager.GetString("strLblFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font {0}, size {1}.
        /// </summary>
        internal static string strLblFontName {
            get {
                return ResourceManager.GetString("strLblFontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size: {0}.
        /// </summary>
        internal static string strLblFontSize {
            get {
                return ResourceManager.GetString("strLblFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font style: {0}.
        /// </summary>
        internal static string strLblFontStyle {
            get {
                return ResourceManager.GetString("strLblFontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a model to start working with:.
        /// </summary>
        internal static string strLblSelect {
            get {
                return ResourceManager.GetString("strLblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set zoom level.
        /// </summary>
        internal static string strLblZoom {
            get {
                return ResourceManager.GetString("strLblZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string strMenuMainFile {
            get {
                return ResourceManager.GetString("strMenuMainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit....
        /// </summary>
        internal static string strMenuMainFileExit {
            get {
                return ResourceManager.GetString("strMenuMainFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New....
        /// </summary>
        internal static string strMenuMainFileNew {
            get {
                return ResourceManager.GetString("strMenuMainFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string strMenuMainHelp {
            get {
                return ResourceManager.GetString("strMenuMainHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string strMenuMainHelpAbout {
            get {
                return ResourceManager.GetString("strMenuMainHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Window.
        /// </summary>
        internal static string strMenuMainWindow {
            get {
                return ResourceManager.GetString("strMenuMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit
        ///the application?.
        /// </summary>
        internal static string strMsgBoxExit {
            get {
                return ResourceManager.GetString("strMsgBoxExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit?.
        /// </summary>
        internal static string strMsgBoxExitTitle {
            get {
                return ResourceManager.GetString("strMsgBoxExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twisting angle multiplier (AM):.
        /// </summary>
        internal static string strNIOSH_AM {
            get {
                return ResourceManager.GetString("strNIOSH_AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twisting angle (°):.
        /// </summary>
        internal static string strNIOSH_Angle {
            get {
                return ResourceManager.GetString("strNIOSH_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupling multiplier (CM):.
        /// </summary>
        internal static string strNIOSH_CM {
            get {
                return ResourceManager.GetString("strNIOSH_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupling:.
        /// </summary>
        internal static string strNIOSH_Coupling {
            get {
                return ResourceManager.GetString("strNIOSH_Coupling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial data.
        /// </summary>
        internal static string strNIOSH_Data {
            get {
                return ResourceManager.GetString("strNIOSH_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance multiplier (DM):.
        /// </summary>
        internal static string strNIOSH_DM {
            get {
                return ResourceManager.GetString("strNIOSH_DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task duration (hours):.
        /// </summary>
        internal static string strNIOSH_Duration {
            get {
                return ResourceManager.GetString("strNIOSH_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NIOSH lifting index is computed as follows:.
        /// </summary>
        internal static string strNIOSH_Equation {
            get {
                return ResourceManager.GetString("strNIOSH_Equation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string strNIOSH_EquationIndex {
            get {
                return ResourceManager.GetString("strNIOSH_EquationIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string strNIOSH_EquationWeight {
            get {
                return ResourceManager.GetString("strNIOSH_EquationWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency multiplier (FM):.
        /// </summary>
        internal static string strNIOSH_FM {
            get {
                return ResourceManager.GetString("strNIOSH_FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency A multiplier (FMa):.
        /// </summary>
        internal static string strNIOSH_FMa {
            get {
                return ResourceManager.GetString("strNIOSH_FMa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency B multiplier (FMb):.
        /// </summary>
        internal static string strNIOSH_FMb {
            get {
                return ResourceManager.GetString("strNIOSH_FMb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifting frequency (times/min):.
        /// </summary>
        internal static string strNIOSH_Frequency {
            get {
                return ResourceManager.GetString("strNIOSH_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifting frequency A (times/min):.
        /// </summary>
        internal static string strNIOSH_FrequencyA {
            get {
                return ResourceManager.GetString("strNIOSH_FrequencyA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifting frequency B (times/min):.
        /// </summary>
        internal static string strNIOSH_FrequencyB {
            get {
                return ResourceManager.GetString("strNIOSH_FrequencyB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal multiplier (HM):.
        /// </summary>
        internal static string strNIOSH_HM {
            get {
                return ResourceManager.GetString("strNIOSH_HM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal distance (cm):.
        /// </summary>
        internal static string strNIOSH_HorizontalD {
            get {
                return ResourceManager.GetString("strNIOSH_HorizontalD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifting index (IF):.
        /// </summary>
        internal static string strNIOSH_IF {
            get {
                return ResourceManager.GetString("strNIOSH_IF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NIOSH lifting index is:.
        /// </summary>
        internal static string strNIOSH_Index {
            get {
                return ResourceManager.GetString("strNIOSH_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifting constant (LC):.
        /// </summary>
        internal static string strNIOSH_LC {
            get {
                return ResourceManager.GetString("strNIOSH_LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifting index (LI):.
        /// </summary>
        internal static string strNIOSH_LI {
            get {
                return ResourceManager.GetString("strNIOSH_LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multipliers.
        /// </summary>
        internal static string strNIOSH_Multipliers {
            get {
                return ResourceManager.GetString("strNIOSH_Multipliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtask order:.
        /// </summary>
        internal static string strNIOSH_Order {
            get {
                return ResourceManager.GetString("strNIOSH_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the results obtained from the NIOSH lifting model:.
        /// </summary>
        internal static string strNIOSH_Results {
            get {
                return ResourceManager.GetString("strNIOSH_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical distance (cm):.
        /// </summary>
        internal static string strNIOSH_VerticalD {
            get {
                return ResourceManager.GetString("strNIOSH_VerticalD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical travel distance (cm):.
        /// </summary>
        internal static string strNIOSH_VerticalT {
            get {
                return ResourceManager.GetString("strNIOSH_VerticalT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical multiplier (VM):.
        /// </summary>
        internal static string strNIOSH_VM {
            get {
                return ResourceManager.GetString("strNIOSH_VM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight lifted (kg):.
        /// </summary>
        internal static string strNIOSH_Weight {
            get {
                return ResourceManager.GetString("strNIOSH_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current culture formatting.
        /// </summary>
        internal static string strRadCurrentCulture {
            get {
                return ResourceManager.GetString("strRadCurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invariant culture formatting.
        /// </summary>
        internal static string strRadInvariantCulture {
            get {
                return ResourceManager.GetString("strRadInvariantCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive lifting model (CLM).
        /// </summary>
        internal static string strRadModelCLM {
            get {
                return ResourceManager.GetString("strRadModelCLM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberty Mutual manual handling.
        /// </summary>
        internal static string strRadModelLiberty {
            get {
                return ResourceManager.GetString("strRadModelLiberty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metabolic rate.
        /// </summary>
        internal static string strRadModelMetabolic {
            get {
                return ResourceManager.GetString("strRadModelMetabolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIOSH lifting equation (LI, CLI, SLI, VLI).
        /// </summary>
        internal static string strRadModelNIOSH {
            get {
                return ResourceManager.GetString("strRadModelNIOSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCRA checklist.
        /// </summary>
        internal static string strRadModelOCRA {
            get {
                return ResourceManager.GetString("strRadModelOCRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revised strain index (RSI, COSI, CUSI).
        /// </summary>
        internal static string strRadModelStrain {
            get {
                return ResourceManager.GetString("strRadModelStrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal comfort (PMV, PPD).
        /// </summary>
        internal static string strRadModelThermal {
            get {
                return ResourceManager.GetString("strRadModelThermal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkRest model (1991).
        /// </summary>
        internal static string strRadModelWR {
            get {
                return ResourceManager.GetString("strRadModelWR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select culture.
        /// </summary>
        internal static string strRadUserCulture {
            get {
                return ResourceManager.GetString("strRadUserCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtask.
        /// </summary>
        internal static string strSubTask {
            get {
                return ResourceManager.GetString("strSubTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface.
        /// </summary>
        internal static string strTabGUI {
            get {
                return ResourceManager.GetString("strTabGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text and font.
        /// </summary>
        internal static string strTabPlot {
            get {
                return ResourceManager.GetString("strTabPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string strTask {
            get {
                return ResourceManager.GetString("strTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string strToolStripAbout {
            get {
                return ResourceManager.GetString("strToolStripAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add line.
        /// </summary>
        internal static string strToolStripAddLine {
            get {
                return ResourceManager.GetString("strToolStripAddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string strToolStripDuplicate {
            get {
                return ResourceManager.GetString("strToolStripDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit data.
        /// </summary>
        internal static string strToolStripEdit {
            get {
                return ResourceManager.GetString("strToolStripEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string strToolStripExit {
            get {
                return ResourceManager.GetString("strToolStripExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string strToolStripNew {
            get {
                return ResourceManager.GetString("strToolStripNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open model.
        /// </summary>
        internal static string strToolStripOpen {
            get {
                return ResourceManager.GetString("strToolStripOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove line.
        /// </summary>
        internal static string strToolStripRemoveLine {
            get {
                return ResourceManager.GetString("strToolStripRemoveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string strToolStripSave {
            get {
                return ResourceManager.GetString("strToolStripSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save chart.
        /// </summary>
        internal static string strToolStripSaveChart {
            get {
                return ResourceManager.GetString("strToolStripSaveChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string strToolStripSettings {
            get {
                return ResourceManager.GetString("strToolStripSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this software.
        /// </summary>
        internal static string strToolTipAbout {
            get {
                return ResourceManager.GetString("strToolTipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add line to the current plot.
        /// </summary>
        internal static string strToolTipAddLine {
            get {
                return ResourceManager.GetString("strToolTipAddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select text backcolor.
        /// </summary>
        internal static string strToolTipBackColor {
            get {
                return ResourceManager.GetString("strToolTipBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate the current model.
        /// </summary>
        internal static string strToolTipDuplicate {
            get {
                return ResourceManager.GetString("strToolTipDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current model&apos;s data.
        /// </summary>
        internal static string strToolTipEdit {
            get {
                return ResourceManager.GetString("strToolTipEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        internal static string strToolTipExit {
            get {
                return ResourceManager.GetString("strToolTipExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select font.
        /// </summary>
        internal static string strToolTipFont {
            get {
                return ResourceManager.GetString("strToolTipFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select font color.
        /// </summary>
        internal static string strToolTipFontColor {
            get {
                return ResourceManager.GetString("strToolTipFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new ergonomics model.
        /// </summary>
        internal static string strToolTipNew {
            get {
                return ResourceManager.GetString("strToolTipNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open data-file model from disk.
        /// </summary>
        internal static string strToolTipOpen {
            get {
                return ResourceManager.GetString("strToolTipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove line from the current plot.
        /// </summary>
        internal static string strToolTipRemoveLine {
            get {
                return ResourceManager.GetString("strToolTipRemoveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data and results to disk.
        /// </summary>
        internal static string strToolTipSave {
            get {
                return ResourceManager.GetString("strToolTipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save chart picture to disk.
        /// </summary>
        internal static string strToolTipSaveChart {
            get {
                return ResourceManager.GetString("strToolTipSaveChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for models, data, and UI.
        /// </summary>
        internal static string strToolTipSettings {
            get {
                return ResourceManager.GetString("strToolTipSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface language.
        /// </summary>
        internal static string strToolTipUILanguage {
            get {
                return ResourceManager.GetString("strToolTipUILanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap words to the beginning of the next line.
        /// </summary>
        internal static string strToolTipWordWrap {
            get {
                return ResourceManager.GetString("strToolTipWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select zoom factor.
        /// </summary>
        internal static string strToolTipZoom {
            get {
                return ResourceManager.GetString("strToolTipZoom", resourceCulture);
            }
        }
    }
}
