//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoCalc.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErgoCalc.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select culture.
        /// </summary>
        internal static string strFormLanguageTitle {
            get {
                return ResourceManager.GetString("strFormLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErgoCalc.
        /// </summary>
        internal static string strFormMainTitle {
            get {
                return ResourceManager.GetString("strFormMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string strFormTitleUnion {
            get {
                return ResourceManager.GetString("strFormTitleUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string strMenuMainFile {
            get {
                return ResourceManager.GetString("strMenuMainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit....
        /// </summary>
        internal static string strMenuMainFileExit {
            get {
                return ResourceManager.GetString("strMenuMainFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New....
        /// </summary>
        internal static string strMenuMainFileNew {
            get {
                return ResourceManager.GetString("strMenuMainFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string strMenuMainHelp {
            get {
                return ResourceManager.GetString("strMenuMainHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string strMenuMainHelpAbout {
            get {
                return ResourceManager.GetString("strMenuMainHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Window.
        /// </summary>
        internal static string strMenuMainWindow {
            get {
                return ResourceManager.GetString("strMenuMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current culture formatting.
        /// </summary>
        internal static string strRadCurrentCulture {
            get {
                return ResourceManager.GetString("strRadCurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invariant culture formatting.
        /// </summary>
        internal static string strRadInvariantCulture {
            get {
                return ResourceManager.GetString("strRadInvariantCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select culture.
        /// </summary>
        internal static string strRadUserCulture {
            get {
                return ResourceManager.GetString("strRadUserCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string strToolStripAbout {
            get {
                return ResourceManager.GetString("strToolStripAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add line.
        /// </summary>
        internal static string strToolStripAddLine {
            get {
                return ResourceManager.GetString("strToolStripAddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string strToolStripDuplicate {
            get {
                return ResourceManager.GetString("strToolStripDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit data.
        /// </summary>
        internal static string strToolStripEdit {
            get {
                return ResourceManager.GetString("strToolStripEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string strToolStripExit {
            get {
                return ResourceManager.GetString("strToolStripExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string strToolStripNew {
            get {
                return ResourceManager.GetString("strToolStripNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open model.
        /// </summary>
        internal static string strToolStripOpen {
            get {
                return ResourceManager.GetString("strToolStripOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove line.
        /// </summary>
        internal static string strToolStripRemoveLine {
            get {
                return ResourceManager.GetString("strToolStripRemoveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string strToolStripSave {
            get {
                return ResourceManager.GetString("strToolStripSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save chart.
        /// </summary>
        internal static string strToolStripSaveChart {
            get {
                return ResourceManager.GetString("strToolStripSaveChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string strToolStripSettings {
            get {
                return ResourceManager.GetString("strToolStripSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this software.
        /// </summary>
        internal static string strToolTipAbout {
            get {
                return ResourceManager.GetString("strToolTipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add line to the current plot.
        /// </summary>
        internal static string strToolTipAddLine {
            get {
                return ResourceManager.GetString("strToolTipAddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate the current model.
        /// </summary>
        internal static string strToolTipDuplicate {
            get {
                return ResourceManager.GetString("strToolTipDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current model&apos;s data.
        /// </summary>
        internal static string strToolTipEdit {
            get {
                return ResourceManager.GetString("strToolTipEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        internal static string strToolTipExit {
            get {
                return ResourceManager.GetString("strToolTipExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new ergonomics model.
        /// </summary>
        internal static string strToolTipNew {
            get {
                return ResourceManager.GetString("strToolTipNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open data-file model from disk.
        /// </summary>
        internal static string strToolTipOpen {
            get {
                return ResourceManager.GetString("strToolTipOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove line from the current plot.
        /// </summary>
        internal static string strToolTipRemoveLine {
            get {
                return ResourceManager.GetString("strToolTipRemoveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data and results to disk.
        /// </summary>
        internal static string strToolTipSave {
            get {
                return ResourceManager.GetString("strToolTipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save chart picture to disk.
        /// </summary>
        internal static string strToolTipSaveChart {
            get {
                return ResourceManager.GetString("strToolTipSaveChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for models, data, and UI.
        /// </summary>
        internal static string strToolTipSettings {
            get {
                return ResourceManager.GetString("strToolTipSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface language.
        /// </summary>
        internal static string strToolTipUILanguage {
            get {
                return ResourceManager.GetString("strToolTipUILanguage", resourceCulture);
            }
        }
    }
}
